# Generated by Django 4.0.6 on 2022-07-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewind',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='rewind',
            old_name='programme_attended',
            new_name='programme',
        ),
    ]
