# Generated by Django 4.0.6 on 2022-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_rename_name_rewind_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewind',
            name='programme',
            field=models.CharField(choices=[(1, 'Rewind'), (2, 'Renew'), (3, 'Restart')], max_length=20),
        ),
    ]
