# Generated by Django 4.0.6 on 2022-07-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_alter_rewind_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewind',
            name='name1',
        ),
    ]
