# Generated by Django 4.0.6 on 2022-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0008_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.AlterField(
            model_name='rewind',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
