# Generated by Django 4.0.6 on 2022-07-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_delete_booking_alter_rewind_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='renew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, null=True)),
                ('programme', models.CharField(choices=[('Rewind', 'Rewind'), ('Renew', 'Renew'), ('Restart', 'Restart')], default='Renew', max_length=10)),
                ('date', models.CharField(choices=[('12/05/2023-19/05/2023', '12/05/2023-19/05/2023'), ('09/06/2023-16/06/2023', '09/06/2023-16/06/2023'), ('15/07/2023-22/07/2023', '15/07/2023-22/07/2023'), ('02/08/2023-09/08/2023', '02/08/2023-09/08/2023'), ('20/08/2023-27/08/2023', '20/08/2023-27/08/2023')], default='12/05/2023-19/05/2023', max_length=25)),
                ('status', models.CharField(default='approved', max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='restart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, null=True)),
                ('programme', models.CharField(choices=[('Rewind', 'Rewind'), ('Renew', 'Renew'), ('Restart', 'Restart')], default='Restart', max_length=10)),
                ('date', models.CharField(choices=[('13/05/2023-18/05/2023', '13/05/2023-18/05/2023'), ('24/05/2023-29/05/2023', '24/05/2023-29/05/2023'), ('08/06/2023-13/06/2023', '08/06/2023-12/06/2023'), ('21/06/2023-26/06/2023', '21/06/2023-26/06/2023'), ('13/07/2023-18/07/2023', '13/07/2023-18/07/2023'), ('15/08/2023-20/08/2023', '15/08/2023-20/08/2023')], default='13/05/2023-18/05/2023', max_length=25)),
                ('status', models.CharField(default='approved', max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='rewind',
            name='date',
            field=models.CharField(choices=[('05/05/2023-08/05/2023', '05/05/2023-08/05/2023'), ('14/05/2023-17/05/2023', '14/05/2023-17/05/2023'), ('25/05/2023-28/05/2023', '25/05/2023-28/05/2023'), ('04/06/2023-07/06/2023', '04/06/2023-07/06/2023'), ('14/06/2023-17/06/2023', '14/06/2023-17/06/2023'), ('04/07/2023-07/07/2023', '04/07/2023-07/07/2023'), ('12/07/2023-15/07/2023', '12/07/2023-15/07/2023'), ('22/07/2023-25/07/2023', '22/07/2023-25/07/2023'), ('08/08/2023-11/08/2023', '08/08/2023-11/08/2023')], default='05/05/2023-08/05/2023', max_length=25),
        ),
        migrations.AlterField(
            model_name='rewind',
            name='status',
            field=models.CharField(default='approved', max_length=10),
        ),
    ]
