# Generated by Django 4.0.6 on 2022-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_renew_restart_alter_rewind_date_alter_rewind_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renew',
            name='programme',
            field=models.CharField(default='Renew', max_length=10),
        ),
        migrations.AlterField(
            model_name='restart',
            name='programme',
            field=models.CharField(default='Restart', max_length=10),
        ),
        migrations.AlterField(
            model_name='rewind',
            name='programme',
            field=models.CharField(default='Rewind', max_length=10),
        ),
    ]
