# Generated by Django 4.0.6 on 2022-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='newUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=20)),
                ('userPasswordRepeat', models.CharField(max_length=20)),
            ],
        ),
    ]
